name: CI/CD Pipeline

# Defines when the action should run. 
on:
  push:
    branches: [ main-website ] # Replace 'main' with your default branch if different.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14' # Set this to your project's node version

    - name: Install Dependencies
      run: npm install

    - name: Run Build
      run: npm run build

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "build/"
        target: "/path/to/target"
 